title: Site

columns:
  - width: 1/2
    sections:
      portfolio: sections/portfolios
  - width: 1/2
    sections:
      perspectives: sections/perspectives
      life: sections/lifes         
      pages:
        type: pages
        create: 
          - default
          - bio
          - jumbotron
        template:
          - about
          - home
          - default
          - jumbotron
          - bio
      notes: sections/notes