title: Site

columns:
  - width: 1/2
    sections:
      albums: sections/albums
  - width: 1/2
    sections:
      portfolio: sections/portfolios 
      perspectives: sections/perspectives
      life: sections/lifes         
      notes: sections/notes
      pages:
        type: pages
        create: default
        template:
          - about
          - home
          - default
